# This is a simplified test workflow that does not include tests that require a connection to server.
# If tests are successful and the push is a tag, then run a test-deploy to test.pypi.org.

name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install required Linux library for pykerberos
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install libkrb5-dev

      - name: Install Poetry
        run: |
          pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
          cache: 'poetry'

      - name: Check pyproject.toml validity
        run: poetry check --no-interaction

      - name: Install deps
        run: poetry install --no-interaction

      - name: Run tests
        run: poetry run pytest
